# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: master 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - 
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - 
      name: Get project version
      run:  |
            version=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)
            echo "PROJECT_VERSION=$version" >> $GITHUB_ENV
    - 
      name: Build with Maven
      run: mvn clean package -DskipTests
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: rogercode
        password: Ra1Re2Ri3
    - 
      name: Show directory
      run: echo $(pwd)
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: rogercode/basic-backend:${{ env.PROJECT_VERSION }}
        context: ./
    - 
      name: Show directory
      run: echo $(pwd)
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
